#pragma config(Sensor, port5,  shootlight,     sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port11, getlight,       sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          c1,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          L,             tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor3,          in1,           tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          c2,            tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          R,             tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor9,          in2,           tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int thingval=1;
	while(true)
	{
		//driving
		motor[R] = vexRT(ChA);
		motor[L] = vexRT(ChD);

		//intake
		if(vexRT(BtnRDown) == 1){setMultipleMotors(127,in1,in2,noMotor,noMotor);}
		if(vexRT(BtnLDown) == 1){setMultipleMotors(-127,in1,in2,noMotor,noMotor);}
		if(vexRT(BtnRDown)==0 && vexRT(BtnLDown)==0){stopMultipleMotors(in1,in2,noMotor,noMotor);}

		//beambreak
		if((getColorGrayscale(getlight)<100)&&(vexRT(BtnFDown)!=1)){
			stopMultipleMotors(c1,c2);
			thingval=0;
		}else{thingval=1;}

		if(vexRT(BtnFUp)&&thingval==1){
			setMultipleMotors(127,c1,c2);
		}else if(vexRT(BtnEUp)){
			setMultipleMotors(-127,c1,c2);
		}else{
			setMultipleMotors(0,c1,c2);
		}



	}
}
